/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.IntelliJTheme;
import java.util.Vector;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.Blueberry;
import model.FruitAndNuts;
import model.HardChocolateCoating;
import model.IceCream;
import model.MeltedMarshmallow;
import model.Oreos;
import model.Sprinkles;
import model.Strawberry;

/**
 *
 * @author NUWAA
 */
public class SnowDen extends javax.swing.JFrame {

    IceCream icecream;
    double total;

    /**
     * Creates new form SnowDen
     */
    public SnowDen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        strawberryButton = new javax.swing.JButton();
        blueberryButton = new javax.swing.JButton();
        fruitAndNutsButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        oreosButton = new javax.swing.JButton();
        meltedMarshmallowButton = new javax.swing.JButton();
        hardChocolateCoatingButton = new javax.swing.JButton();
        sprinklesButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        addNewButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snow Den");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ice Cream", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        strawberryButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        strawberryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-ice-cream-25 (1).png"))); // NOI18N
        strawberryButton.setText("Strawberry");
        strawberryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberryButtonActionPerformed(evt);
            }
        });

        blueberryButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        blueberryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-ice-cream-25.png"))); // NOI18N
        blueberryButton.setText("Blueberry");
        blueberryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueberryButtonActionPerformed(evt);
            }
        });

        fruitAndNutsButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fruitAndNutsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-banana-split-25.png"))); // NOI18N
        fruitAndNutsButton.setText("Fruit And Nuts");
        fruitAndNutsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitAndNutsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(strawberryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueberryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fruitAndNutsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(strawberryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(blueberryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fruitAndNutsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Toppings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        oreosButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        oreosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-oreo-25.png"))); // NOI18N
        oreosButton.setText("Oreos");
        oreosButton.setEnabled(false);
        oreosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oreosButtonActionPerformed(evt);
            }
        });

        meltedMarshmallowButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        meltedMarshmallowButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-marshmallow-25.png"))); // NOI18N
        meltedMarshmallowButton.setText("Melted Marshmallow");
        meltedMarshmallowButton.setEnabled(false);
        meltedMarshmallowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltedMarshmallowButtonActionPerformed(evt);
            }
        });

        hardChocolateCoatingButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        hardChocolateCoatingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-chocolate-25.png"))); // NOI18N
        hardChocolateCoatingButton.setText("Hard Chocolate Coating");
        hardChocolateCoatingButton.setEnabled(false);
        hardChocolateCoatingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardChocolateCoatingButtonActionPerformed(evt);
            }
        });

        sprinklesButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sprinklesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-donut-25.png"))); // NOI18N
        sprinklesButton.setText("Sprinkles");
        sprinklesButton.setEnabled(false);
        sprinklesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sprinklesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hardChocolateCoatingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oreosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meltedMarshmallowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sprinklesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oreosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hardChocolateCoatingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meltedMarshmallowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sprinklesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        descriptionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Description", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(descriptionTable);
        if (descriptionTable.getColumnModel().getColumnCount() > 0) {
            descriptionTable.getColumnModel().getColumn(1).setMinWidth(250);
            descriptionTable.getColumnModel().getColumn(1).setMaxWidth(250);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Total : Rs.");

        totalLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalLabel.setText("0.0");

        addNewButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addNewButton.setText("Add New");
        addNewButton.setEnabled(false);
        addNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(addNewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalLabel))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setText("Snow Den");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void strawberryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberryButtonActionPerformed
        // TODO add your handling code here:
        icecream = new Strawberry();
        int rowCount = descriptionTable.getRowCount();
        descriptionTable.setValueAt(icecream.getDescription(), rowCount - 1, 0);
        descriptionTable.setValueAt(icecream.cost(), rowCount - 1, 1);

        buttonSetEnable();

        total = 0.0;
        for (int i = 0; i < descriptionTable.getRowCount(); i++) {
            total = total + Double.parseDouble(descriptionTable.getValueAt(i, 1).toString());
        }
        totalLabel.setText(String.valueOf(total));
    }//GEN-LAST:event_strawberryButtonActionPerformed

    private void blueberryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueberryButtonActionPerformed
        // TODO add your handling code here:
        icecream = new Blueberry();
        int rowCount = descriptionTable.getRowCount();
        descriptionTable.setValueAt(icecream.getDescription(), rowCount - 1, 0);
        descriptionTable.setValueAt(icecream.cost(), rowCount - 1, 1);

        buttonSetEnable();

        total = 0.0;
        for (int i = 0; i < descriptionTable.getRowCount(); i++) {
            total = total + Double.parseDouble(descriptionTable.getValueAt(i, 1).toString());
        }
        totalLabel.setText(String.valueOf(total));
    }//GEN-LAST:event_blueberryButtonActionPerformed

    private void fruitAndNutsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitAndNutsButtonActionPerformed
        // TODO add your handling code here:
        icecream = new FruitAndNuts();
        int rowCount = descriptionTable.getRowCount();
        descriptionTable.setValueAt(icecream.getDescription(), rowCount - 1, 0);
        descriptionTable.setValueAt(icecream.cost(), rowCount - 1, 1);

        buttonSetEnable();

        total = 0.0;
        for (int i = 0; i < descriptionTable.getRowCount(); i++) {
            total = total + Double.parseDouble(descriptionTable.getValueAt(i, 1).toString());
        }
        totalLabel.setText(String.valueOf(total));
    }//GEN-LAST:event_fruitAndNutsButtonActionPerformed

    private void oreosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oreosButtonActionPerformed
        // TODO add your handling code here:
        icecream = new Oreos(icecream);
        int rowCount = descriptionTable.getRowCount();
        descriptionTable.setValueAt(icecream.getDescription(), rowCount - 1, 0);
        descriptionTable.setValueAt(icecream.cost(), rowCount - 1, 1);
        total = 0.0;
        for (int i = 0; i < descriptionTable.getRowCount(); i++) {
            total = total + Double.parseDouble(descriptionTable.getValueAt(i, 1).toString());
        }
        totalLabel.setText(String.valueOf(total));
    }//GEN-LAST:event_oreosButtonActionPerformed

    private void hardChocolateCoatingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardChocolateCoatingButtonActionPerformed
        // TODO add your handling code here:
        icecream = new HardChocolateCoating(icecream);

        int rowCount = descriptionTable.getRowCount();
        descriptionTable.setValueAt(icecream.getDescription(), rowCount - 1, 0);
        descriptionTable.setValueAt(icecream.cost(), rowCount - 1, 1);
        total = 0.0;
        for (int i = 0; i < descriptionTable.getRowCount(); i++) {
            total = total + Double.parseDouble(descriptionTable.getValueAt(i, 1).toString());
        }
        totalLabel.setText(String.valueOf(total));
    }//GEN-LAST:event_hardChocolateCoatingButtonActionPerformed

    private void meltedMarshmallowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltedMarshmallowButtonActionPerformed
        // TODO add your handling code here:
        icecream = new MeltedMarshmallow(icecream);
        int rowCount = descriptionTable.getRowCount();
        descriptionTable.setValueAt(icecream.getDescription(), rowCount - 1, 0);
        descriptionTable.setValueAt(icecream.cost(), rowCount - 1, 1);
        total = 0.0;
        for (int i = 0; i < descriptionTable.getRowCount(); i++) {
            total = total + Double.parseDouble(descriptionTable.getValueAt(i, 1).toString());
        }
        totalLabel.setText(String.valueOf(total));
    }//GEN-LAST:event_meltedMarshmallowButtonActionPerformed

    private void sprinklesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sprinklesButtonActionPerformed
        // TODO add your handling code here:
        icecream = new Sprinkles(icecream);
        int rowCount = descriptionTable.getRowCount();
        descriptionTable.setValueAt(icecream.getDescription(), rowCount - 1, 0);
        descriptionTable.setValueAt(icecream.cost(), rowCount - 1, 1);
        total = 0.0;
        for (int i = 0; i < descriptionTable.getRowCount(); i++) {
            total = total + Double.parseDouble(descriptionTable.getValueAt(i, 1).toString());
        }
        totalLabel.setText(String.valueOf(total));
    }//GEN-LAST:event_sprinklesButtonActionPerformed

    private void addNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) descriptionTable.getModel();
        dtm.addRow(new Vector());
    }//GEN-LAST:event_addNewButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SnowDen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SnowDen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SnowDen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SnowDen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        try {
//            UIManager.setLookAndFeel(new FlatLightLaf());
            IntelliJTheme.setup(SnowDen.class.getResourceAsStream(
                    "/resources/themes/arc-theme.theme.json"));
            UIManager.put("Table.showHorizontalLines", true);
            UIManager.put("Table.showVerticalLines", true);
            UIManager.put("ScrollBar.showButtons", true);
            UIManager.put("ScrollBar.width", 16);
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnowDen().setVisible(true);
            }
        });
    }

    private void buttonSetEnable() {
        oreosButton.setEnabled(true);
        hardChocolateCoatingButton.setEnabled(true);
        meltedMarshmallowButton.setEnabled(true);
        sprinklesButton.setEnabled(true);
        addNewButton.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewButton;
    private javax.swing.JButton blueberryButton;
    private javax.swing.JTable descriptionTable;
    private javax.swing.JButton fruitAndNutsButton;
    private javax.swing.JButton hardChocolateCoatingButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton meltedMarshmallowButton;
    private javax.swing.JButton oreosButton;
    private javax.swing.JButton sprinklesButton;
    private javax.swing.JButton strawberryButton;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables

}
